# the name of the pipeline
name: CI

# create events that will trigger the pipeline
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

# create a job with the name 'build' (a set of steps that will run on the Virtual machine)
jobs:
  build:
    runs-on: ubuntu-latest # specify the OS of the Virtual Machine provided by GitHub
    defaults:
      run:
        working-directory: ./python-app # navigate to the folder where all the commands will run

    # define steps for the job to do
    steps:
      # checkout the whole repository to the Linux Virtual Machine using predefined GitHub action
      - name: Checkout repository
        uses: actions/checkout@v5

      # build development image - tests run automatically at this step
      - name: Build development Docker image
        run: docker build --target development --build-arg NAME=Alina -t python-app:dev .

      # build production image - runs only if development build and tests passed
      - name: Build production Docker image
        run: docker build --target production --build-arg NAME=Alina -t python-app:prod .

  # create a job with the name 'test' that runs tests only when the build job completed successfully
  test:
    needs: build # wait for build job to complete before running
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-app

    steps:
    # checkout the repository to the Linux Virtual Machine
      - name: Checkout repository
        uses: actions/checkout@v5
        
      # set up Python on the VM
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      # install dependencies including pytest
      - name: Install dependencies
        run: pip install ".[dev]"

      # run tests on the VM
      - name: Run tests
        run: pytest tests/test_app.py
